import { useEffect, useState } from "react";
import { BellRing, CheckCircle2, Clock3, FileCheck2, History, KeyRound, Loader2, Search, ShieldAlert, SlidersHorizontal, Trash2, XCircle } from "lucide-react";
import DashboardLayout from "@/components/DashboardLayout";
import { useAuth } from "@/_core/hooks/useAuth";
import { trpc } from "@/lib/trpc";
import { canAccessAdminDashboard } from "@/lib/adminDashboardUtils";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Switch } from "@/components/ui/switch";
import { Textarea } from "@/components/ui/textarea";
import { GovernanceAnalyticsCharts } from "@/components/GovernanceAnalyticsCharts";
import { toast } from "sonner";

type PermissionKey = "canExportCsv" | "canExportPdf" | "canVerifyReferences" | "canViewTeamDownloadHistory" | "canManageExportPermissions";
type VerifiedReference = { referenceCode: string; exportedAt: Date; exportedByName: string | null; exportedByEmail: string | null; download?: { downloadedAt: Date; rowCount: number; filterSummary: string } } | null;
type DecisionTarget = { id: number; approve: boolean } | null;
const permissionLabels: Array<[PermissionKey, string]> = [["canExportCsv", "ส่งออก CSV"], ["canExportPdf", "ส่งออก PDF"], ["canVerifyReferences", "ตรวจ Reference"], ["canViewTeamDownloadHistory", "ดูประวัติทีม"], ["canManageExportPermissions", "จัดการสิทธิ์"]];
const statusClass: Record<string, string> = { pending: "bg-amber-500/15 text-amber-700 dark:text-amber-300", approved: "bg-emerald-500/15 text-emerald-700 dark:text-emerald-300", rejected: "bg-rose-500/15 text-rose-700 dark:text-rose-300", expired: "bg-muted text-muted-foreground" };
const severityClass: Record<string, string> = { high: "bg-rose-500/15 text-rose-700 dark:text-rose-300", warning: "bg-amber-500/15 text-amber-700 dark:text-amber-300", info: "bg-primary/10 text-primary" };

export default function ReportGovernance() {
  const { user } = useAuth();
  const utils = trpc.useUtils();
  const canView = Boolean(user && canAccessAdminDashboard(user.role));
  const [referenceCode, setReferenceCode] = useState("");
  const [verifiedReference, setVerifiedReference] = useState<VerifiedReference>(null);
  const [hasCheckedReference, setHasCheckedReference] = useState(false);
  const [isVerifying, setIsVerifying] = useState(false);
  const [decisionTarget, setDecisionTarget] = useState<DecisionTarget>(null);
  const [reviewerNote, setReviewerNote] = useState("");
  const [policyForm, setPolicyForm] = useState({ highVolumeRowThreshold: 500, approvalRowThreshold: 750, retentionDays: 365, approvalExpiresHours: 24, alertOwnerOnHighVolume: true });
  const { data: ownPermissions, isLoading: permissionsLoading, error: permissionsError } = trpc.admin.getMyExportPermissions.useQuery(undefined, { enabled: canView });
  const canManage = Boolean(ownPermissions?.canManageExportPermissions);
  const { data: policy, isLoading: policyLoading, error: policyError } = trpc.admin.getExportSecurityPolicy.useQuery(undefined, { enabled: canView });
  const { data: downloadHistory = [], isLoading: historyLoading, error: historyError } = trpc.admin.getMyReportDownloadHistory.useQuery({ limit: 100 }, { enabled: canView });
  const { data: adminPermissions = [] } = trpc.admin.listAdminExportPermissions.useQuery(undefined, { enabled: canView && canManage });
  const { data: myRequests = [], isLoading: requestsLoading, error: requestsError } = trpc.admin.getMyExportApprovalRequests.useQuery({ limit: 50 }, { enabled: canView });
  const { data: pendingRequests = [], isLoading: pendingLoading, error: pendingError } = trpc.admin.getPendingExportApprovalRequests.useQuery({ limit: 100 }, { enabled: canView && canManage });
  const { data: securityEvents = [], isLoading: eventsLoading, error: eventsError } = trpc.admin.getRecentExportSecurityEvents.useQuery({ limit: 50 }, { enabled: canView && canManage });
  const { data: analytics, isLoading: analyticsLoading, error: analyticsError } = trpc.admin.getGovernanceAnalytics.useQuery({ days: 30 }, { enabled: canView && canManage });
  const { data: notifications = [], isLoading: notificationsLoading, error: notificationsError } = trpc.loan.getNotifications.useQuery(undefined, { enabled: canView && canManage });
  const approvalNotifications = notifications.filter((notification) => notification.type === "export_approval_pending");
  const unreadApprovalNotifications = approvalNotifications.filter((notification) => !notification.isRead);
  const updatePermission = trpc.admin.updateAdminExportPermissions.useMutation({ onSuccess: () => { utils.admin.listAdminExportPermissions.invalidate(); toast.success("อัปเดตสิทธิ์ส่งออกแล้ว"); }, onError: (error) => toast.error(error.message) });
  const updatePolicy = trpc.admin.updateExportSecurityPolicy.useMutation({ onSuccess: () => { utils.admin.getExportSecurityPolicy.invalidate(); toast.success("บันทึกนโยบาย Report Governance แล้ว"); } });
  const decideRequest = trpc.admin.decideExportApprovalRequest.useMutation({ onSuccess: () => { utils.admin.getPendingExportApprovalRequests.invalidate(); utils.admin.getMyExportApprovalRequests.invalidate(); utils.admin.getRecentExportSecurityEvents.invalidate(); utils.admin.getGovernanceAnalytics.invalidate(); setDecisionTarget(null); setReviewerNote(""); toast.success("บันทึกผลการพิจารณาแล้ว"); } });
  const runCleanup = trpc.admin.runDownloadHistoryRetentionCleanup.useMutation({ onSuccess: (result) => { utils.admin.getMyReportDownloadHistory.invalidate(); utils.admin.getRecentExportSecurityEvents.invalidate(); toast.success(`ล้างประวัติแล้ว: ดาวน์โหลด ${result.deletedHistory} รายการ, เหตุการณ์ ${result.deletedEvents} รายการ`); } });
  const markApprovalNotificationRead = trpc.loan.markAsRead.useMutation({ onSuccess: () => { utils.loan.getNotifications.invalidate(); } });

  useEffect(() => { if (policy) setPolicyForm({ highVolumeRowThreshold: policy.highVolumeRowThreshold, approvalRowThreshold: policy.approvalRowThreshold, retentionDays: policy.retentionDays, approvalExpiresHours: policy.approvalExpiresHours, alertOwnerOnHighVolume: policy.alertOwnerOnHighVolume }); }, [policy]);

  const verifyReference = async () => {
    const normalized = referenceCode.trim().toUpperCase();
    if (!/^AUD-\d{14}-[A-F0-9]{8}$/.test(normalized)) return toast.error("กรุณากรอก Reference Code รูปแบบ AUD-YYYYMMDDHHMMSS-XXXXXXXX");
    try { setIsVerifying(true); setHasCheckedReference(false); setVerifiedReference(await utils.admin.verifyAuditLogPdfReference.fetch({ referenceCode: normalized })); setHasCheckedReference(true); } catch (error) { toast.error(error instanceof Error ? error.message : "ไม่สามารถตรวจสอบ Reference Code ได้"); } finally { setIsVerifying(false); }
  };
  const changePermission = (row: Record<PermissionKey | "userId", boolean | number>, key: PermissionKey, value: boolean) => updatePermission.mutate({ userId: Number(row.userId), canExportCsv: Boolean(row.canExportCsv), canExportPdf: Boolean(row.canExportPdf), canVerifyReferences: Boolean(row.canVerifyReferences), canViewTeamDownloadHistory: Boolean(row.canViewTeamDownloadHistory), canManageExportPermissions: Boolean(row.canManageExportPermissions), [key]: value });
  const savePolicy = async () => {
    if (policyForm.approvalRowThreshold < policyForm.highVolumeRowThreshold) return toast.error("เกณฑ์อนุมัติต้องไม่น้อยกว่าเกณฑ์แจ้งเตือน");
    try { await updatePolicy.mutateAsync(policyForm); } catch (error) { toast.error(error instanceof Error ? error.message : "ไม่สามารถบันทึกนโยบายได้"); }
  };
  const submitDecision = async () => {
    if (!decisionTarget) return;
    try { await decideRequest.mutateAsync({ requestId: decisionTarget.id, approve: decisionTarget.approve, ...(reviewerNote.trim() ? { reviewerNote: reviewerNote.trim() } : {}) }); } catch (error) { toast.error(error instanceof Error ? error.message : "ไม่สามารถบันทึกผลการพิจารณาได้"); }
  };

  if (!canView) return <DashboardLayout><Card className="mx-auto max-w-xl glass-panel"><CardContent className="p-8 text-center"><ShieldAlert className="mx-auto h-10 w-10 text-destructive" /><h1 className="mt-4 text-xl font-semibold">ไม่มีสิทธิ์เข้าถึงการกำกับรายงาน</h1><p className="mt-2 text-sm text-muted-foreground">หน้านี้สงวนไว้สำหรับผู้ดูแลระบบ</p></CardContent></Card></DashboardLayout>;
  if (permissionsLoading || policyLoading) return <DashboardLayout><div className="mx-auto max-w-6xl space-y-6" role="status" aria-live="polite"><div className="h-28 animate-pulse rounded-2xl bg-muted" /><div className="grid gap-5 lg:grid-cols-2"><div className="h-80 animate-pulse rounded-2xl bg-muted" /><div className="h-80 animate-pulse rounded-2xl bg-muted" /></div></div></DashboardLayout>;
  const pageError = permissionsError || policyError || historyError || requestsError || pendingError || eventsError || analyticsError;
  if (pageError) return <DashboardLayout><Card className="mx-auto max-w-2xl glass-panel"><CardContent className="p-8 text-center"><ShieldAlert className="mx-auto h-10 w-10 text-destructive" /><h1 className="mt-4 text-xl font-semibold">ไม่สามารถโหลด Report Governance ได้</h1><p className="mt-2 text-sm text-destructive">{pageError.message}</p><Button className="mt-5" variant="outline" onClick={() => window.location.reload()}>ลองใหม่</Button></CardContent></Card></DashboardLayout>;

  return <DashboardLayout><main className="mx-auto max-w-6xl space-y-6"><header className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-sm font-medium text-primary">Admin Governance</p><h1 className="text-3xl font-bold tracking-tight">การกำกับรายงาน</h1><p className="mt-1 max-w-3xl text-muted-foreground">ตรวจสอบ PDF กำหนดนโยบาย ตรวจจับการส่งออกปริมาณสูง และใช้ dual-control ก่อนส่งออกข้อมูลระดับสูง</p></div><div className="rounded-xl border border-primary/15 bg-primary/5 px-4 py-3 text-sm"><span className="font-semibold text-primary">{myRequests.filter((request) => request.status === "pending").length}</span><span className="ml-1 text-muted-foreground">คำขอของฉันที่รอดำเนินการ</span></div></header>

  {canManage && <><GovernanceAnalyticsCharts analytics={analytics} isLoading={analyticsLoading} /><Card className="glass-panel"><CardHeader><div className="flex gap-3"><BellRing className="mt-0.5 h-6 w-6 text-primary" /><div><CardTitle>การแจ้งเตือนคำขอรออนุมัติ</CardTitle><CardDescription>แจ้งเฉพาะผู้มีสิทธิ์อนุมัติคนอื่นผ่าน in-app notification</CardDescription></div></div></CardHeader><CardContent>{notificationsLoading ? <p className="text-sm text-muted-foreground">กำลังโหลดการแจ้งเตือน…</p> : notificationsError ? <p className="rounded-xl bg-rose-500/10 p-4 text-sm text-rose-700 dark:text-rose-300">ไม่สามารถโหลดการแจ้งเตือนได้: {notificationsError.message}</p> : approvalNotifications.length ? <div className="max-h-56 space-y-3 overflow-y-auto pr-1">{approvalNotifications.map((notification) => <div key={notification.id} className="flex items-start justify-between gap-3 rounded-xl border border-border/70 p-3 text-sm"><div><p className="font-medium">{notification.message}</p><p className="mt-1 text-xs text-muted-foreground">{new Date(notification.createdAt).toLocaleString("th-TH")}</p></div>{notification.isRead ? <Badge className="bg-muted text-muted-foreground">อ่านแล้ว</Badge> : <Button size="sm" variant="outline" onClick={() => markApprovalNotificationRead.mutate({ notificationId: notification.id })} disabled={markApprovalNotificationRead.isPending}>ทำเครื่องหมายอ่านแล้ว</Button>}</div>)}</div> : <p className="rounded-xl bg-muted/60 p-5 text-sm text-muted-foreground">ยังไม่มีการแจ้งเตือนคำขออนุมัติสำหรับบัญชีนี้</p>}{unreadApprovalNotifications.length > 0 && <p className="mt-3 text-xs font-medium text-primary">ยังไม่ได้อ่าน {unreadApprovalNotifications.length.toLocaleString("th-TH")} รายการ</p>}</CardContent></Card></>}

  <div className="grid gap-5 lg:grid-cols-2"><Card className="glass-panel"><CardHeader><div className="flex gap-3"><FileCheck2 className="mt-0.5 h-6 w-6 text-primary" /><div><CardTitle>ตรวจสอบ Reference Code</CardTitle><CardDescription>ค้นหา metadata ของ PDF Audit Logs โดยไม่เปิดเผยข้อมูลในรายงาน</CardDescription></div></div></CardHeader><CardContent className="space-y-4"><div className="flex flex-col gap-2 sm:flex-row"><Input value={referenceCode} onChange={(event) => setReferenceCode(event.target.value.toUpperCase())} placeholder="AUD-YYYYMMDDHHMMSS-XXXXXXXX" aria-label="Reference Code ของ PDF" /><Button type="button" onClick={verifyReference} disabled={isVerifying || !ownPermissions?.canVerifyReferences} className="gap-2"><Search className="h-4 w-4" />{isVerifying ? "กำลังตรวจสอบ" : "ตรวจสอบ"}</Button></div>{ownPermissions && !ownPermissions.canVerifyReferences && <p className="text-sm text-amber-700 dark:text-amber-300">บัญชีนี้ไม่มีสิทธิ์ตรวจสอบ Reference Code</p>}{hasCheckedReference && !verifiedReference && <p className="rounded-lg border border-amber-300 bg-amber-50 p-3 text-sm text-amber-900">ไม่พบ Reference Code นี้ในระบบ</p>}{verifiedReference && <div className="grid gap-3 rounded-xl border border-primary/15 bg-primary/5 p-4 text-sm sm:grid-cols-2"><div><span className="text-muted-foreground">Reference</span><p className="font-mono font-semibold">{verifiedReference.referenceCode}</p></div><div><span className="text-muted-foreground">สร้างเมื่อ</span><p className="font-medium">{new Date(verifiedReference.exportedAt).toLocaleString("th-TH")}</p></div><div><span className="text-muted-foreground">ผู้ส่งออก</span><p className="font-medium">{verifiedReference.exportedByName || "ไม่ระบุชื่อ"}</p></div><div><span className="text-muted-foreground">สถานะดาวน์โหลด</span><p className="font-medium">{verifiedReference.download ? `บันทึกแล้ว ${new Date(verifiedReference.download.downloadedAt).toLocaleString("th-TH")}` : "ยังไม่มีประวัติการดาวน์โหลด"}</p></div></div>}</CardContent></Card>
  <Card className="glass-panel"><CardHeader><div className="flex gap-3"><SlidersHorizontal className="mt-0.5 h-6 w-6 text-primary" /><div><CardTitle>นโยบายการส่งออก</CardTitle><CardDescription>กำหนด threshold, retention และอายุคำอนุมัติ</CardDescription></div></div></CardHeader><CardContent className="space-y-4"><div className="grid gap-3 sm:grid-cols-2"><label className="text-sm font-medium">เกณฑ์แจ้งเตือน (แถว)<Input className="mt-1" type="number" min={1} max={1000} disabled={!canManage} value={policyForm.highVolumeRowThreshold} onChange={(event) => setPolicyForm((form) => ({ ...form, highVolumeRowThreshold: Number(event.target.value) }))} /></label><label className="text-sm font-medium">เกณฑ์ต้องอนุมัติ (แถว)<Input className="mt-1" type="number" min={1} max={1000} disabled={!canManage} value={policyForm.approvalRowThreshold} onChange={(event) => setPolicyForm((form) => ({ ...form, approvalRowThreshold: Number(event.target.value) }))} /></label><label className="text-sm font-medium">เก็บ download history (วัน)<Input className="mt-1" type="number" min={30} max={3650} disabled={!canManage} value={policyForm.retentionDays} onChange={(event) => setPolicyForm((form) => ({ ...form, retentionDays: Number(event.target.value) }))} /></label><label className="text-sm font-medium">อายุคำอนุมัติ (ชั่วโมง)<Input className="mt-1" type="number" min={1} max={168} disabled={!canManage} value={policyForm.approvalExpiresHours} onChange={(event) => setPolicyForm((form) => ({ ...form, approvalExpiresHours: Number(event.target.value) }))} /></label></div><div className="flex items-center justify-between gap-3 rounded-xl border border-primary/15 bg-primary/5 p-3"><div><Label htmlFor="export-alert">แจ้งเตือนผู้ดูแลโครงการ</Label><p className="text-xs text-muted-foreground">เมื่อบันทึกการส่งออกตั้งแต่เกณฑ์แจ้งเตือน</p></div><Switch id="export-alert" checked={policyForm.alertOwnerOnHighVolume} disabled={!canManage} onCheckedChange={(checked) => setPolicyForm((form) => ({ ...form, alertOwnerOnHighVolume: checked }))} /></div>{canManage ? <div className="flex flex-wrap gap-2"><Button onClick={savePolicy} disabled={updatePolicy.isPending}>{updatePolicy.isPending && <Loader2 className="mr-2 h-4 w-4 animate-spin" />}บันทึกนโยบาย</Button><Button type="button" variant="outline" onClick={() => runCleanup.mutate()} disabled={runCleanup.isPending}>{runCleanup.isPending && <Loader2 className="mr-2 h-4 w-4 animate-spin" />}<Trash2 className="mr-2 h-4 w-4" />ล้างประวัติตามนโยบาย</Button></div> : <p className="text-sm text-muted-foreground">คุณสามารถดูนโยบายได้ แต่ไม่มีสิทธิ์แก้ไขหรือล้างประวัติ</p>}<p className="rounded-lg bg-muted/60 p-3 text-xs text-muted-foreground">งานล้างอัตโนมัติรายวันจะต้องตั้งค่า Heartbeat หลังเผยแพร่ระบบก่อน ระหว่างนี้ผู้มีสิทธิ์สั่งล้างตามนโยบายได้ด้วยตนเอง</p></CardContent></Card></div>

  <div className="grid gap-5 lg:grid-cols-2"><Card className="glass-panel"><CardHeader><div className="flex gap-3"><Clock3 className="mt-0.5 h-6 w-6 text-primary" /><div><CardTitle>คำขอส่งออกของฉัน</CardTitle><CardDescription>คำขอผูกกับรูปแบบ จำนวนแถว และเงื่อนไขตัวกรองเดิม</CardDescription></div></div></CardHeader><CardContent>{requestsLoading ? <p className="text-sm text-muted-foreground">กำลังโหลดคำขอ…</p> : myRequests.length ? <div className="max-h-96 space-y-3 overflow-y-auto pr-1">{myRequests.map((request) => <div key={request.id} className="rounded-xl border border-border/70 p-3 text-sm"><div className="flex items-start justify-between gap-3"><div><p className="font-semibold">{request.format.toUpperCase()} · {request.rowCount.toLocaleString("th-TH")} แถว</p><p className="mt-1 text-xs text-muted-foreground">{request.filterSummary || "ไม่มีตัวกรองเพิ่มเติม"}</p></div><Badge className={statusClass[request.status]}>{request.status}</Badge></div><p className="mt-2 text-xs text-muted-foreground">หมดอายุ: {new Date(request.expiresAt).toLocaleString("th-TH")}</p>{request.reviewerNote && <p className="mt-2 rounded bg-muted/60 p-2 text-xs">หมายเหตุ: {request.reviewerNote}</p>}</div>)}</div> : <p className="rounded-xl bg-muted/60 p-5 text-sm text-muted-foreground">ยังไม่มีคำขออนุมัติการส่งออกข้อมูลระดับสูง</p>}</CardContent></Card>
  <Card className="glass-panel"><CardHeader><div className="flex gap-3"><History className="mt-0.5 h-6 w-6 text-primary" /><div><CardTitle>ประวัติการดาวน์โหลดของฉัน</CardTitle><CardDescription>เก็บเฉพาะ metadata ไม่เก็บเนื้อหารายงาน</CardDescription></div></div></CardHeader><CardContent>{historyLoading ? <p className="text-sm text-muted-foreground">กำลังโหลดประวัติ…</p> : downloadHistory.length ? <div className="max-h-96 space-y-3 overflow-y-auto pr-1">{downloadHistory.map((row) => <div key={row.id} className="rounded-xl border border-border/70 p-3 text-sm"><div className="flex justify-between gap-3"><p className="font-semibold">{row.format.toUpperCase()} · {row.rowCount.toLocaleString("th-TH")} แถว</p><time className="text-xs text-muted-foreground">{new Date(row.createdAt).toLocaleString("th-TH")}</time></div><p className="mt-1 truncate text-xs text-muted-foreground" title={row.filterSummary}>{row.filterSummary || "ไม่มีตัวกรอง"}</p>{row.referenceCode && <p className="mt-1 font-mono text-xs text-primary">{row.referenceCode}</p>}</div>)}</div> : <p className="rounded-xl bg-muted/60 p-5 text-sm text-muted-foreground">ยังไม่มีประวัติการดาวน์โหลดรายงานของบัญชีนี้</p>}</CardContent></Card></div>

  {canManage && <><Card className="glass-panel"><CardHeader><div className="flex gap-3"><ShieldAlert className="mt-0.5 h-6 w-6 text-primary" /><div><CardTitle>กล่องคำขอรออนุมัติ</CardTitle><CardDescription>ผู้ขอไม่สามารถอนุมัติคำขอของตนเองได้</CardDescription></div></div></CardHeader><CardContent>{pendingLoading ? <p className="text-sm text-muted-foreground">กำลังโหลดคำขอ…</p> : pendingRequests.length ? <div className="grid gap-3 md:grid-cols-2">{pendingRequests.map((request) => <div key={request.id} className="rounded-xl border border-border/70 p-4"><div className="flex items-start justify-between gap-3"><div><p className="font-semibold">คำขอ #{request.id} · {request.format.toUpperCase()}</p><p className="mt-1 text-sm text-muted-foreground">{request.rowCount.toLocaleString("th-TH")} แถว · {request.filterSummary || "ไม่มีตัวกรอง"}</p></div><Badge className={statusClass.pending}>pending</Badge></div><p className="mt-3 text-xs text-muted-foreground">หมดอายุ: {new Date(request.expiresAt).toLocaleString("th-TH")}</p><div className="mt-4 flex gap-2"><Button size="sm" onClick={() => setDecisionTarget({ id: request.id, approve: true })}><CheckCircle2 className="mr-1 h-4 w-4" />อนุมัติ</Button><Button size="sm" variant="outline" onClick={() => setDecisionTarget({ id: request.id, approve: false })}><XCircle className="mr-1 h-4 w-4" />ปฏิเสธ</Button></div></div>)}</div> : <p className="rounded-xl bg-muted/60 p-5 text-sm text-muted-foreground">ไม่มีคำขอที่รอการอนุมัติ</p>}</CardContent></Card>
  <Card className="glass-panel"><CardHeader><CardTitle>เหตุการณ์ความปลอดภัยล่าสุด</CardTitle><CardDescription>บันทึก alert และผลการควบคุมการส่งออกโดยไม่เปิดเผยข้อมูลรายงาน</CardDescription></CardHeader><CardContent>{eventsLoading ? <p className="text-sm text-muted-foreground">กำลังโหลดเหตุการณ์…</p> : securityEvents.length ? <div className="max-h-80 space-y-3 overflow-y-auto pr-1">{securityEvents.map((event) => <div key={event.id} className="flex items-start justify-between gap-3 rounded-xl border border-border/70 p-3 text-sm"><div><p className="font-medium">{event.message}</p><p className="mt-1 text-xs text-muted-foreground">{new Date(event.createdAt).toLocaleString("th-TH")}{event.rowCount ? ` · ${event.rowCount.toLocaleString("th-TH")} แถว` : ""}</p></div><Badge className={severityClass[event.severity]}>{event.severity}</Badge></div>)}</div> : <p className="rounded-xl bg-muted/60 p-5 text-sm text-muted-foreground">ยังไม่มีเหตุการณ์ความปลอดภัย</p>}</CardContent></Card>
  <Card className="glass-panel"><CardHeader><div className="flex gap-3"><KeyRound className="mt-0.5 h-6 w-6 text-primary" /><div><CardTitle>สิทธิ์ส่งออกรายบัญชี</CardTitle><CardDescription>ระบบตรวจสิทธิ์ซ้ำบน server ทุกครั้งที่ส่งออก</CardDescription></div></div></CardHeader><CardContent><div className="space-y-3">{adminPermissions.map((row) => <div key={row.userId} className="rounded-xl border border-border/70 p-4"><div className="mb-3"><p className="font-medium">{row.name || "ไม่ระบุชื่อ"}</p><p className="text-sm text-muted-foreground">{row.email || "ไม่มีอีเมล"}</p></div><div className="flex flex-wrap gap-x-5 gap-y-3">{permissionLabels.map(([key, label]) => <label key={key} className="flex items-center gap-2 text-sm"><input type="checkbox" checked={Boolean(row[key])} disabled={updatePermission.isPending} onChange={(event) => changePermission(row, key, event.target.checked)} />{label}</label>)}</div></div>)}</div></CardContent></Card></>}
  </main><Dialog open={Boolean(decisionTarget)} onOpenChange={(open) => { if (!open) { setDecisionTarget(null); setReviewerNote(""); } }}><DialogContent className="glass-panel"><DialogHeader><DialogTitle>{decisionTarget?.approve ? "อนุมัติคำขอส่งออก" : "ปฏิเสธคำขอส่งออก"}</DialogTitle><DialogDescription>ระบบจะบันทึกการตัดสินใจเป็นเหตุการณ์ความปลอดภัย</DialogDescription></DialogHeader><Label htmlFor="reviewer-note">หมายเหตุ (ไม่บังคับ)</Label><Textarea id="reviewer-note" value={reviewerNote} maxLength={500} onChange={(event) => setReviewerNote(event.target.value)} placeholder="บันทึกเหตุผลหรือเงื่อนไขที่เกี่ยวข้อง" /><DialogFooter><Button variant="outline" onClick={() => setDecisionTarget(null)}>ยกเลิก</Button><Button variant={decisionTarget?.approve ? "default" : "destructive"} onClick={submitDecision} disabled={decideRequest.isPending}>{decideRequest.isPending && <Loader2 className="mr-2 h-4 w-4 animate-spin" />}{decisionTarget?.approve ? "ยืนยันอนุมัติ" : "ยืนยันปฏิเสธ"}</Button></DialogFooter></DialogContent></Dialog></DashboardLayout>;
}
