import React, { useMemo } from "react";
import { Bar } from "react-chartjs-2";
import { BarChart3 } from "lucide-react";
import { Chart as ChartJS, CategoryScale, LinearScale, BarElement, Tooltip, Legend } from "chart.js";
import { Card } from "@/components/ui/card";

ChartJS.register(CategoryScale, LinearScale, BarElement, Tooltip, Legend);

export function ActivityHistoryDailyChart({ daily, isLoading, onDaySelect }: { daily: Array<{ date: string; count: number }>; isLoading: boolean; onDaySelect?: (date: string) => void }) {
  const chartData = useMemo(() => ({ labels: daily.map((item) => new Date(`${item.date}T00:00:00`).toLocaleDateString("th-TH", { day: "numeric", month: "short" })), datasets: [{ label: "จำนวนกิจกรรม", data: daily.map((item) => item.count), backgroundColor: "rgba(37, 99, 235, 0.78)", borderRadius: 8, maxBarThickness: 42 }] }), [daily]);
  return <Card className="glass-panel p-5"><div className="flex items-center gap-2"><BarChart3 className="h-5 w-5 text-primary" /><div><h2 className="font-semibold">กิจกรรมรายวัน</h2><p className="mt-0.5 text-sm text-muted-foreground">คลิกแท่งกราฟเพื่อดูรายละเอียดของวันนั้น</p></div></div>{isLoading ? <div className="mt-5 h-52 animate-pulse rounded-xl bg-muted" role="status" aria-live="polite" aria-busy="true" /> : daily.length ? <><div className="mt-5 h-56"><Bar data={chartData} options={{ maintainAspectRatio: false, responsive: true, onClick: (_event, elements) => { const index = elements[0]?.index; if (index !== undefined) onDaySelect?.(daily[index].date); }, plugins: { legend: { display: false }, tooltip: { displayColors: false } }, scales: { x: { grid: { display: false } }, y: { beginAtZero: true, ticks: { precision: 0 }, grid: { color: "rgba(148, 163, 184, 0.16)" } } } }} /></div><div className="mt-4 flex flex-wrap gap-2" aria-label="เลือกวันจากกราฟ"><span className="text-xs text-muted-foreground">เลือกวัน:</span>{daily.map((item) => <button key={item.date} type="button" onClick={() => onDaySelect?.(item.date)} className="rounded-full border border-primary/20 px-2.5 py-1 text-xs font-medium text-primary hover:bg-primary/10">{new Date(`${item.date}T00:00:00`).toLocaleDateString("th-TH", { day: "numeric", month: "short" })} · {item.count}</button>)}</div></> : <div className="mt-5 flex h-52 flex-col items-center justify-center rounded-xl border border-dashed border-border/80 text-center"><BarChart3 className="h-8 w-8 text-muted-foreground/60" /><p className="mt-2 text-sm font-medium">ยังไม่มีข้อมูลสำหรับกราฟ</p><p className="mt-1 text-xs text-muted-foreground">ปรับตัวกรองเพื่อดูภาพรวมกิจกรรมรายวัน</p></div>}</Card>;
}
